<!--A Design by ps.jayachandran
Author: http://alagianallur.eu5.org/
Author URL: http://w3layouts.com
License Life Time Free
-->
<!DOCTYPE html>
<html>
<head>
<title>Clean India</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Agendo Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<link href="css2/bootstrap.css" rel="stylesheet" type="text/css" media="all"/>
	<!--theme-style-->
	<link href="css2/style.css" rel="stylesheet" type="text/css" media="all" />	
	<!--//theme-style-->
    <!-- animated-css -->
		<link href="css2/animate.css" rel="stylesheet" type="text/css" media="all">
		<script src="js2/wow.min.js"></script>
		<script>
		 new WOW().init();
		</script>
	<!-- animated-css -->
	<!--fonts-->
	<link href="css2/font-awesome.css" rel="stylesheet" type="text/css" media="all" />	
	<!--//fonts-->
    <script type="text/javascript" src="js2/wow.min.js"></script>
	<script type="text/javascript" src="js2/jquery-1.11.0.min.js"></script>
	<script type="text/javascript" src="js2/move-top.js"></script>
	<script type="text/javascript" src="js2/easing.js"></script>
	<script type="text/javascript">
			jQuery(document).ready(function($) {
			$(".scroll").click(function(event){		
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
			});
		});
	</script>
    <link href="css2/silder.css" rel="stylesheet" media="all">
    <link href="js2/fancybox/source/jquery.fancybox.css" rel="stylesheet" />               
    <script src="js2/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
    <script src="js2/bootstrap.min.js" type="text/javascript"></script>      
    <script src="js2/jquery.touchSwipe.min.js"></script>
	<script src="js2/silder.js"></script>
    <script type="text/javascript" src="js2/fancybox/source/jquery.fancybox.pack.js"></script>
    <script src="js2/jquery.mixitup.min.js"></script>    
    <script src="js2/app.js"></script>
    <script src="js2/portfolio.js"></script> 
    <script type="text/javascript">
        jQuery(document).ready(function() {
            App.init();
            Portfolio.init();                      
        });
    </script>
	<script type="text/javascript" src="js2/jquery.flexisel.js"></script>
    <script type="text/javascript" src="js2/mypassion.js"></script>
</head>
<body>
<div id="loading-mask">
	<div class="loading-img"><img src="images2/loading4.gif" alt="MyPassion" /></div>
</div>

<!--  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   		Start menu part
  	 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  -->
<div class="header">
  <div class="container">
	<div class="logo">
		<img src="images2/logo.png " alt="" />
	</div>
    <div class="menu">
	   
	   <ul class="nav" id="nav">
		 <li><a href="home.php">Home</a></li>
		  <li><a href="aboutus.php">About Us</a></li>
		 <li><a href="registration.php">Registration</a></li>
		 <li><a href="login.php">Login</a></li>
		  <li><a href="contactus.php">Contact Us</a></li>
		 <li><a href="feedback.php">Feedback</a></li>
		 	
	  </ul>
	  <script type="text/javascript" src="js2/responsive-nav.js"></script>
	</div>							
    <div class="clearfix"> </div>
	<!----//End-top-nav---->
  </div>
</div>
