<?php include 'header2.php'; ?>



		<div id="full_width_carousel" class="carousel slide animate_text full_width_carousel_wrapper" data-ride="carousel" data-interval="6000" data-pause="hover">
			<div class="carousel-inner" role="listbox">
				<div class="item active">
					<img src="images2/slide1.jpg" alt="slide 1" />
					<div class="carousel-caption full_width_carousel_caption" data-animation="animated fadeInUp">
						
					
					</div>
				</div>
				<div class="item">
					<img src="images2/slide2.jpg" alt="slide 2" />
					<div class="carousel-caption full_width_carousel_caption full_width_carousel_caption_right" data-animation="animated fadeInUp">
						
					
					</div>
				</div>
				<div class="item">
					<img src="images2/slide3.jpg" alt="slide 3" />
					<div class="carousel-caption full_width_carousel_caption full_width_carousel_caption_center" data-animation="animated fadeInUp">
						
					</div>
				</div>
				
				
				<div class="item">
					<img src="images2/slide4.jpg" alt="slide 3" />
					<div class="carousel-caption full_width_carousel_caption full_width_carousel_caption_center" data-animation="animated fadeInUp">
						
					</div>
				</div>
				
				
				<div class="item">
					<img src="images2/slide5.jpg" alt="slide 3" />
					<div class="carousel-caption full_width_carousel_caption full_width_carousel_caption_center" data-animation="animated fadeInUp">
						
					</div>
				</div>
				
				
				

			</div>
				<a class="left carousel-control full_width_carousel_control_left" href="#full_width_carousel" role="button" data-slide="prev">
				<span class="fa fa-angle-double-left full_width_carousel_control_icons" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>
			<a class="right carousel-control full_width_carousel_control_right" href="#full_width_carousel" role="button" data-slide="next">
				<span class="fa fa-angle-double-right full_width_carousel_control_icons" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>

		</div> 	







<div id="team">
	<div class="container">
   		 <div class="team">
         	<h2> Meet The <span> Team </span> </h2>
  		  </div>
          
          	
            
           <div class="col-md-3">
            	<div class="member wow bounceInRight" data-wow-delay="0.5s">
                	  <div class="view view-fifth">
                			<img src="images2/aa.jpg" alt="" title="Team Member">
                   	 		<h4>Shubham Lohar</h4>
                             		<div class="social facebooks">
											<a href="#"> <i class="fa fa-facebook"> </i></a>
										</div>
                                         <div class="social plus">
											<a href="#"> <i class="fa fa-linkedin"> </i></a>
										</div>
                                         <div class="social twi">
											<a href="#"> <i class="fa  fa-twitter"> </i></a>
										</div>
                                         <div class="social read">
											<a href="#"> <i class="fa  fa-rss"> </i></a>
										</div>
               		 			</div>			
           		 </div>
           	</div>
            <div class="col-md-3">
            	<div class="member wow bounceInRight" data-wow-delay="0.5s">
                	  <div class="view view-fifth">
                			<img src="images2/kk.jpg" alt="" title="Team Member">
                   	 		<h4>Sneha Maisurya</h4>
                             		<div class="social facebooks">
											<a href="#"> <i class="fa fa-facebook"> </i></a>
										</div>
                                         <div class="social plus">
											<a href="#"> <i class="fa fa-linkedin"> </i></a>
										</div>
                                         <div class="social twi">
											<a href="#"> <i class="fa  fa-twitter"> </i></a>
										</div>
                                         <div class="social read">
											<a href="#"> <i class="fa  fa-rss"> </i></a>
										</div>
               		 			</div>			
           		 </div>
           	</div>
                    
         
    </div>
</div>
 







<?php include 'footer2.php'; ?>