<?php include'header3.php';?>

 <div id="page-wrapper">
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                           <h1 class="page-head-line"><center>HOME</center></h1>
                    </div>
                </div>
				
				
				
				
				
                <div class="row">
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-12">

                                <div id="reviews" class="carousel slide" data-ride="carousel">

                                    <div class="carousel-inner">
                                        <div class="item active">

                                            <div class="col-md-10 col-md-offset-1">

                                                <h4><font color=""><b>"</b><B><i>one step toword clean india.</i></b><b>"</b></font></h4>
                                                <div class="user-img pull-right">
                                                    <img src="images2/shubhu.jpg" alt="" class="img-u image-responsive" />
                                                </div>
                                                <h5 class="pull-right"><strong class="c-black">Shubham Lohar</strong></h5>
                                            </div>
                                        </div>
                                        <div class="item">
                                            <div class="col-md-10 col-md-offset-1">

                                                <h4><b>"</b><b><i><font color="white">keep clean our india make green our india.</font></b></i><b>"</b></h4>
                                                <div class="user-img pull-right">
                                                    <img src="assets/img3/user3.jpg" alt="" class="img-u image-responsive" />
                                                </div>
                                                <h5 class="pull-right"><strong class="c-black">Pratik Desai</strong></h5>
                                            </div>

                                        </div>
                                        <div class="item">
                                            <div class="col-md-10 col-md-offset-1">

                                                <h4><b>"</b><b><i>clean city clean india green world.</i></b><b>"</b> </h4>
                                                <div class="user-img pull-right">
                                                    <img src="assets/img3/user4.jpg" alt="" class="img-u image-responsive" />
                                                </div>
                                                <h5 class="pull-right"><strong class="c-black">Arpit Jivani</strong></h5>
                                            </div>
                                        </div>
                                    </div>
                                    <!--INDICATORS-->
                                    <ol class="carousel-indicators">
                                        <li data-target="#reviews" data-slide-to="0" class="active"></li>
                                        <li data-target="#reviews" data-slide-to="1"></li>
                                        <li data-target="#reviews" data-slide-to="2"></li>
                                    </ol>
                                    <!--PREVIUS-NEXT BUTTONS-->

                                </div>

                            </div>

                        </div>
                        
                    </div>

				
				
				
				
				
				
				
				
			</div>
 </div>
 </div>
 
 
 
 
 
 
 

<?php include'footer3.php';?>