<?php include'header.php'?>


<section class="login-page">
			<div class="inner-banner demo-2 text-center">
				<header class="logo">
					<h1><a class="cd-logo link link--takiri" href="home.php">Clean India <span>Make Clean Our India.</span></a></h1>
				</header>
				<div id="breadcrumb_wrapper">
					<div class="container">		
						<h2>News</h2>
						<h6></h6>
					</div>
				</div>
			</div>

News Is Now Not Available


</section>

<?php include'footer.php'?>