<html>
<head>
	<link rel="stylesheet" type="text/css" href="css/stylesheet7.css">
</head>
<body>
	<h1>CREATE AN ADVERTISE FOR SELL</h1>
	<form action="upload1.php" method="post" enctype="multipart/form-data" >
	
	Book Title:<input type="text" name="title" placeholder="Booktitle"><br>
	Author Name:<input type="text" name="aname" placeholder="Authorname"><br>
	Book Price:<input type="text" name="price" placeholder="Bookprice"><br>
	  Book image: <input type="file" name="image"  ><br>
	  Seller Name:<input type="text" name="sellername" placeholder="Sellername"><br>
	  Seller Location:<input type="text" name="location" placeholder="Location"><br>
	  Seller Number:<input type="text" name="sellernum" placeholder="Sellenumber"><br>
	    Seller Email:<input type="text" name="selleremail" placeholder="Email">
	  

		<input type="submit" value="upload" name="submit">
	
	
	</form>
</body>
</html>