<html>
<head>
	<link rel="stylesheet" type="text/css" href="css/stylesheet7.css">
</head>
<body>
	<h1>CREATE AN ADVERTISE FOR SELL</h1>
	<form action="upload1.php" method="post" enctype="multipart/form-data">
	<div class="add">
	Book Title:<input type="text" name="title" placeholder="Booktitle">
	Author Name:<input type="text" name="aname" placeholder="Authorname">
	Book Price:<input type="text" name="price" placeholder="Bookprice">
	  Book image: <input type="file" name="image"  >
	  
	</div>
		<input type="submit" value="upload" name="submit">
	
	
	</form>
</body>
</html>